/* 
 * JavaScript for ADVANCE website. This is the expanded main script file with comments to understand what
  * each section does. Do not edit this file directly unless adding something new; 
  * instead, edit the min file and rebuild.
 */

//clock on homepage
// Clock
    var clockID = 0;

    function UpdateClock() {
      if(clockID) {
        clearTimeout(clockID);
        clockID  = 0;
      }

      var tDate = new Date();
      document.getElementById("theTime").textContent = 
        tDate.getHours().toString().padStart(2,'0') + ":" +
        tDate.getMinutes().toString().padStart(2,'0') + ":" +
        tDate.getSeconds().toString().padStart(2,'0');
      
      clockID = setTimeout(UpdateClock, 1000);
    }

    function StartClock() {
      clockID = setTimeout(UpdateClock, 500);
    }

    function KillClock() {
      if(clockID) {
        clearTimeout(clockID);
        clockID  = 0;
      }
    }
window.addEventListener('load', StartClock);
window.addEventListener('unload', KillClock);

// typewriter function
function typeWriterEffect(elementId, text, speed = 50, callback) {
  const target = document.getElementById(elementId);
  let i = 0;

  function type() {
    if (i < text.length) {
      target.textContent += text.charAt(i);
      i++;
      setTimeout(type, speed);
    } else if (callback) {
      callback(); // start the next one
    }
  }

  target.textContent = ""; // reset text if reused
  type();
}

// typewriter reveal
function stagedTypewriter(elements) {
  let index = 0;

  function next() {
    if (index < elements.length) {
      const { id, text, speed } = elements[index];
      typeWriterEffect(id, text, speed, next);
      index++;
    }
  }

  next(); 
}

// Run on homepage load
document.addEventListener("DOMContentLoaded", function () {
  stagedTypewriter([
    { id: "typewriter", text: "Advance" , speed: 400 },
    { id: "quote", text: "The mark of a leader." },
    { id: "welcome", text: "Welcome to the revived site!" },
    { id: "mission", text: "Advance is where we are paving the way for tomorrow's leaders!" }
  ]);
  
});





/* Mobile Navigation */

// Navbar mobile toggle and active-link highlighting + events carousel
document.addEventListener('DOMContentLoaded', function () {
  var navToggle = document.querySelector('.nav-toggle');
  var siteNav = document.querySelector('.site-nav');

  function normalizePath(path) {
    if (!path) return 'index.html';
    // remove query and hash, strip trailing slash
    path = path.split('?')[0].split('#')[0].replace(/\/$/, '');
    var base = path.split('/').pop();
    return base || 'index.html';
  }

  if (navToggle && siteNav) {
    navToggle.addEventListener('click', function (e) {
      var expanded = navToggle.getAttribute('aria-expanded') === 'true';
      navToggle.setAttribute('aria-expanded', String(!expanded));
      siteNav.classList.toggle('open');
      if (!expanded) {
        // optionally move focus to first link for accessibility
        var first = siteNav.querySelector('a');
        if (first) first.focus();
      }
    });

    // Close menu when clicking outside
    document.addEventListener('click', function (e) {
      if (!siteNav.contains(e.target) && !navToggle.contains(e.target)) {
        siteNav.classList.remove('open');
        navToggle.setAttribute('aria-expanded', 'false');
      }
    });

    // Close on Escape
    document.addEventListener('keydown', function (e) {
      if (e.key === 'Escape' && siteNav.classList.contains('open')) {
        siteNav.classList.remove('open');
        navToggle.setAttribute('aria-expanded', 'false');
        navToggle.focus();
      }
    });
  }

  // Highlight active link based on current path (more robust)
  var links = document.querySelectorAll('.site-nav a');
  var current = normalizePath(window.location.pathname);
  links.forEach(function (a) {
    var href = a.getAttribute('href');
    try {
      var hrefPath = new URL(href, window.location.href).pathname;
      if (normalizePath(hrefPath) === current) {
        a.classList.add('active');
      }
    } catch (err) {
      // ignore malformed hrefs
    }
    // close menu when any nav link is clicked (mobile UX)
    a.addEventListener('click', function () {
      if (siteNav) {
        siteNav.classList.remove('open');
        if (navToggle) navToggle.setAttribute('aria-expanded', 'false');
      }
    });
  });

  // Events carousel rendering (if events-data.js provided window.EVENTS)
  if (window.EVENTS && Array.isArray(window.EVENTS) && window.EVENTS.length) {
    var carousel = document.querySelector('.events-carousel');
    var prevBtn = document.querySelector('.carousel-prev');
    var nextBtn = document.querySelector('.carousel-next');
    // aria-live region for carousel announcements (screen readers)
    var carouselAnnouncer = document.createElement('div');
    carouselAnnouncer.className = 'sr-only carousel-announcer';
    carouselAnnouncer.setAttribute('aria-live', 'polite');
    carouselAnnouncer.setAttribute('aria-atomic', 'true');
    if (carousel) carousel.appendChild(carouselAnnouncer);
    if (carousel) {
      // filter upcoming events
      const today = new Date();
      today.setHours(0, 0, 0, 0);
      const upcomingEvents = window.EVENTS.filter(ev => {
        const eventDate = new Date(ev.date);
        return !isNaN(eventDate) && eventDate >= today;
      });

      // render items
      upcomingEvents.forEach(function (ev, idx) {
        var item = document.createElement('article');
        item.className = 'event-item';
        item.setAttribute('role', 'listitem');
        // normalize path separators to forward slashes (in case data used Windows paths)
        var flyerSrc = (ev.flyer || '').replace(/\\\\/g, '/');
        // include a clear, focusable button to open the lightbox (accessibility)
        item.innerHTML = '\n          <div class="event-flyer-wrap">\n            <img src="' + flyerSrc + '" alt="' + (ev.title || 'Event flyer') + '">\n          </div>\n          <div class="event-meta">\n            <h3>' + (ev.title || '') + '</h3>\n            <time>' + (ev.date || '') + '</time>\n            <p>' + (ev.description || '') + '</p>\n            <button class="view-flyer-btn" type="button" data-index="' + idx + '" aria-label="View flyer for ' + (ev.title || '') + '">View flyer</button>\n          </div>\n        ';
        carousel.appendChild(item);
      });

      // basic navigation helpers
      function scrollNext() {
        var w = carousel.clientWidth;
        carousel.scrollBy({ left: w * 0.9, behavior: 'smooth' });
      }
      function scrollPrev() {
        var w = carousel.clientWidth;
        carousel.scrollBy({ left: -w * 0.9, behavior: 'smooth' });
      }

      if (nextBtn) nextBtn.addEventListener('click', scrollNext);
      if (prevBtn) prevBtn.addEventListener('click', scrollPrev);

      // keyboard nav for carousel
      carousel.addEventListener('keydown', function (e) {
        if (e.key === 'ArrowRight') scrollNext();
        if (e.key === 'ArrowLeft') scrollPrev();
      });
      carousel.addEventListener('scroll', debounce(announceVisible, 150));
      // initial announce
      setTimeout(announceVisible, 300);
    }
  }

  // Render full events list on Events page (if present)
  var eventsListContainer = document.querySelector('.events-list');
  if (eventsListContainer && window.EVENTS && Array.isArray(window.EVENTS)) {
    // clear any placeholder content
    eventsListContainer.innerHTML = '';
    window.EVENTS.forEach(function (ev, idx) {
      var section = document.createElement('section');
      section.className = 'event-full';
      section.innerHTML = '\n        <div class="event-full-inner container">\n          <div class="event-flyer-wrap">\n            <img src="' + ev.flyer + '" alt="' + (ev.title || 'Event flyer') + '">\n          </div>\n          <div class="event-meta">\n            <h3>' + (ev.title || '') + '</h3>\n            <time>' + (ev.date || '') + '</time>\n            <p>' + (ev.description || '') + '</p>\n          </div>\n        </div>\n      ';
      eventsListContainer.appendChild(section);
    });
  }

  
});

function applyAccentToIcons() {
  // detect color variables based on the active page or theme
  const root = document.body || document.documentElement;
  const background = getComputedStyle(root).getPropertyValue("--bg").trim();
  const accent = getComputedStyle(root).getPropertyValue("--accent").trim();

  document.querySelectorAll("lord-icon").forEach(icon => {
    icon.setAttribute("colors", `primary:${background},secondary:${accent}`);
  });
}
  // when page loads update color
window.addEventListener("DOMContentLoaded", () => {
  applyAccentToIcons();
});


// small debounce helper
function debounce(fn, wait) {
  var t;
  return function () {
    var args = arguments;
    clearTimeout(t);
    t = setTimeout(function () { fn.apply(null, args); }, wait);
  };
}

/* Lightbox for full-size flyers */
(function () {
  function createLightbox() {
    var overlay = document.createElement('div');
    overlay.className = 'lightbox-overlay';
    overlay.setAttribute('role', 'dialog');
    overlay.setAttribute('aria-hidden', 'true');

    overlay.innerHTML = '\n      <div class="lightbox-content">\n        <button class="lightbox-close" aria-label="Close">✕</button>\n        <button class="lightbox-prev" aria-label="Previous">◀</button>\n        <img class="lightbox-image" src="" alt="">\n        <button class="lightbox-next" aria-label="Next">▶</button>\n        <div class="lightbox-caption"></div>\n      </div>\n    ';

    document.body.appendChild(overlay);
    return overlay;
  }

  var overlay = createLightbox();
  var imgEl = overlay.querySelector('.lightbox-image');
  var captionEl = overlay.querySelector('.lightbox-caption');
  var closeBtn = overlay.querySelector('.lightbox-close');
  var prevBtn = overlay.querySelector('.lightbox-prev');
  var nextBtn = overlay.querySelector('.lightbox-next');

  var items = []; // {src, alt, caption}
  var current = 0;
  var lastOpener = null;

  function openAt(index) {
    if (!items.length) return;
    current = (index + items.length) % items.length;
    var it = items[current];
    // prefer full-size source for the lightbox when available
    imgEl.src = it.full || it.src;
    imgEl.alt = it.alt || '';
    captionEl.textContent = it.caption || '';
    overlay.setAttribute('aria-hidden', 'false');
    overlay.classList.add('open');
    overlay.dataset.count = items.length;
    // focus management: save last opener and move focus into lightbox
    try { lastOpener = document.activeElement; } catch (e) { lastOpener = null; }
    closeBtn.focus();
    trapFocus(overlay);
  }

  function closeLightbox() {
    overlay.setAttribute('aria-hidden', 'true');
    overlay.classList.remove('open');
    imgEl.src = '';
    releaseFocusTrap();
    // restore focus to the element that opened the lightbox
    if (lastOpener && typeof lastOpener.focus === 'function') {
      lastOpener.focus();
      lastOpener = null;
    }
  }

  function prev() { openAt(current - 1); }
  function next() { openAt(current + 1); }

  closeBtn.addEventListener('click', closeLightbox);
  prevBtn.addEventListener('click', prev);
  nextBtn.addEventListener('click', next);

  overlay.addEventListener('click', function (e) {
    if (e.target === overlay) closeLightbox();
  });

  document.addEventListener('keydown', function (e) {
    if (overlay.classList.contains('open')) {
      if (e.key === 'Escape') closeLightbox();
      if (e.key === 'ArrowLeft') prev();
      if (e.key === 'ArrowRight') next();
    }
  });

  // gather images on page: flyers inside .events-carousel and .events-list
  function registerGallery() {
    items = [];
    // Use the View Flyer buttons to open the lightbox (buttons are rendered with data-index)
    var buttons = document.querySelectorAll('.view-flyer-btn');
    buttons.forEach(function (btn, i) {
      // derive related image info
      var itemEl = btn.closest('.event-item') || btn.closest('.event-full');
      var img = itemEl ? itemEl.querySelector('.event-flyer-wrap img') : null;
      var src = img ? (img.getAttribute('src') || '') : '';
      var alt = img ? img.alt || '' : '';
      var caption = itemEl ? itemEl.querySelector('.event-meta h3')?.textContent : '';
      var full = img && img.dataset.full ? img.dataset.full : null;
      if (!full && window.EVENTS) {
        var norm = src.replace(/\\\\/g, '/');
        var found = window.EVENTS.find(function (e) { return (e.flyer || '').replace(/\\\\/g, '/') === norm || (e.full || '').replace(/\\\\/g, '/') === norm; });
        if (found) full = (found.full || found.flyer || '').replace(/\\\\/g, '/');
      }
      items.push({ src: src, alt: alt, caption: caption, full: full });
      btn.addEventListener('click', function () { openAt(i); });
      // ensure button accessible state
      btn.setAttribute('type', 'button');
    });
  }

  // initialize after DOM ready and also after dynamic render
  document.addEventListener('DOMContentLoaded', registerGallery);
  // also expose a small API for re-registering if images change
  window.LIGHTBOX = { register: registerGallery, openAt: openAt };
})();


// Focus trap helpers used by the lightbox
var _focusTrap = null;
function trapFocus(container) {
  releaseFocusTrap();
  if (!container) return;
  var focusable = container.querySelectorAll('a[href], button, textarea, input, select, [tabindex]:not([tabindex="-1"])');
  focusable = Array.prototype.slice.call(focusable).filter(function (el) { return !el.hasAttribute('disabled'); });
  if (!focusable.length) return;
  var first = focusable[0];
  var last = focusable[focusable.length - 1];
  function keyHandler(e) {
    if (e.key === 'Tab') {
      if (e.shiftKey && document.activeElement === first) {
        e.preventDefault(); last.focus();
      } else if (!e.shiftKey && document.activeElement === last) {
        e.preventDefault(); first.focus();
      }
    }
  }
  _focusTrap = keyHandler;
  document.addEventListener('keydown', keyHandler);
}

function releaseFocusTrap() {
  if (_focusTrap) {
    document.removeEventListener('keydown', _focusTrap);
    _focusTrap = null;
  }
}

/* =========================================================
   Join PAGE: script to load the form 
   ========================================================= */
  document.addEventListener('DOMContentLoaded', function() {
  const loadFormBtn = document.getElementById('load-form');
  
  if (loadFormBtn) {  // Only run if button exists
    loadFormBtn.addEventListener('click', function() {
      // Remove the button
      this.remove();

      // Create iframe
      const iframe = document.createElement('iframe');
      iframe.src = "https://forms.office.com/Pages/ResponsePage.aspx?id=bC4i9cZf60iPA3PbGCA7Y2YHfGb-G5NHpb26fqm2uHlUOFMzRjZCS1RWTzRXRDUyOFlWVVZYMFJMRi4u&embed=true";
      iframe.width = "100%";
      iframe.height = "700";
      iframe.style.border = "none";
      iframe.loading = "lazy";
      iframe.allowFullscreen = true;

      // Add iframe to container
      document.getElementById('form-container').appendChild(iframe);
    });
  }
});

// Preload form in hidden iframe (only on join page)
document.addEventListener('DOMContentLoaded', function() {
  if (document.getElementById('load-form')) {
    // Create hidden iframe to preload
    const preloadFrame = document.createElement('iframe');
    preloadFrame.src = "https://forms.office.com/Pages/ResponsePage.aspx?id=bC4i9cZf60iPA3PbGCA7Y2YHfGb-G5NHpb26fqm2uHlUOFMzRjZCS1RWTzRXRDUyOFlWVVZYMFJMRi4u&embed=true";
    preloadFrame.style.display = 'none';
    preloadFrame.style.visibility = 'hidden';
    preloadFrame.style.position = 'absolute';
    preloadFrame.style.width = '1px';
    preloadFrame.style.height = '1px';
    document.body.appendChild(preloadFrame);
  }
});


/* =========================================================
   EVENTS PAGE: render square cards into Upcoming & Past
   Uses window.EVENTS provided by events-data.js
   ========================================================= */
(function () {
  // --- helpers ---
  function parseDate(raw) {
    if (!raw) return null;
    const s = String(raw).trim().toUpperCase();



    // "TBD" (or contains TBD) => unknown date, treat as UPCOMING
    if (s.includes('TBD')) return null;

    // "Nov–Dec 2025" (or similar) => first day of first month
    const m = s.match(/(JAN|FEB|MAR|APR|MAY|JUN|JUL|AUG|SEP|OCT|NOV|DEC)[A-Z\-\s]*?(\d{4})/i);
    if (m) {
      const months = 'JAN FEB MAR APR MAY JUN JUL AUG SEP OCT NOV DEC'.split(' ');
      const mi = months.indexOf(m[1].toUpperCase());
      if (mi >= 0) return new Date(Number(m[2]), mi, 1);
    }

    // ISO YYYY-MM-DD
    if (/^\d{4}-\d{2}-\d{2}$/.test(s)) return new Date(s);

    // US MM-DD-YYYY
    if (/^\d{2}-\d{2}-\d{4}$/.test(s)) {
      const [mm, dd, yyyy] = s.split('-').map(Number);
      return new Date(yyyy, mm - 1, dd);
    }

    // anything else = unknown (keep as upcoming)
    return null;
  }

  function formatDateObj(d, rawFallback) {
    return d
      ? d.toLocaleDateString(undefined, { year: 'numeric', month: 'short', day: '2-digit' })
      : (rawFallback || 'TBD');
  }

  function byDateAsc(a, b) {
    const da = parseDate(a.date), db = parseDate(b.date);
    if (da && db) return da - db;
    if (da && !db) return -1;   // known dates before unknown
    if (!da && db) return 1;
    return (a.title || '').localeCompare(b.title || '');
  }

  // --- square card markup (matches your “boxes”) ---
  function eventCard(ev) {
    const d = parseDate(ev.date);
    const dateTxt = formatDateObj(d, ev.date);
    const flyer = (ev.flyer || '').replace(/\\/g, '/'); // normalize windows paths

    return `
      <article class="ev-card" data-id="${ev.id || ''}">
        <img src="${flyer}" alt="${(ev.title || 'Event')} flyer">
        <div class="ev-meta">
          <h3 class="ev-title">${ev.title || ''}</h3>
          <time class="ev-date">${dateTxt}</time>
          <p class="ev-desc">${ev.description || ''}</p>
        </div>
      </article>
    `;
  }

  function renderEvents() {
    if (!Array.isArray(window.EVENTS)) return;

    const today = new Date(); today.setHours(0,0,0,0);

    const upcoming = [];
    const past = [];

    window.EVENTS.forEach(ev => {
      const d = parseDate(ev.date);
      // null/unknown or future => UPCOMING
      if (!d || d >= today) upcoming.push(ev);
      else past.push(ev);
    });

    upcoming.sort(byDateAsc);
    past.sort(byDateAsc).reverse(); // newest past first

    const upGrid = document.getElementById('upcoming-grid');
    const pGrid  = document.getElementById('past-grid');
    const upEmpty = document.getElementById('upcoming-empty');
    const pEmpty  = document.getElementById('past-empty');

    if (upGrid) {
      upGrid.innerHTML = upcoming.map(eventCard).join('');
      if (upEmpty) upEmpty.style.display = upcoming.length ? 'none' : '';
    }
    if (pGrid) {
      pGrid.innerHTML = past.map(eventCard).join('');
      if (pEmpty) pEmpty.style.display = past.length ? 'none' : '';
    }
  }

  // Run after the rest of Kaden's DOMContentLoaded logic
  if (document.readyState === 'loading') {
    document.addEventListener('DOMContentLoaded', renderEvents);
  } else {
    renderEvents();
  }
})();


// Executive board scroll reveal
document.addEventListener('DOMContentLoaded', function () {
  const fadeElements = document.querySelectorAll('.fade-in');
  const observer = new IntersectionObserver(entries => {
    entries.forEach(entry => {
      if (entry.isIntersecting) {
        entry.target.classList.add('visible');
      }
    });
  }, { threshold: 0.2 });

  fadeElements.forEach(el => observer.observe(el));
});

/* Executive Board: background gradient on scroll
   Observes sections with class `.exec-row` and reads their
   `data-bg` (comma-separated colors) and `data-text` (text color)
   to update the fixed `#bg-transition` element and the page text color.
*/
// Executive Board cinematic crossfade background + text transition
document.addEventListener("DOMContentLoaded", () => {
  const sections = document.querySelectorAll(".exec-row");
  const bgA = document.getElementById("bg-transition");
  const bgB = document.getElementById("bg-transition-alt");
  const body = document.body;

  let currentIndex = -1;
  let useA = true;

  function getSectionProgress() {
    const scrollY = window.scrollY + window.innerHeight / 2;
    for (let i = 0; i < sections.length - 1; i++) {
      const rect1 = sections[i].getBoundingClientRect();
      const rect2 = sections[i + 1].getBoundingClientRect();
      const mid1 = rect1.top + window.scrollY;
      const mid2 = rect2.top + window.scrollY;

      if (scrollY >= mid1 && scrollY <= mid2) {
        const ratio = (scrollY - mid1) / (mid2 - mid1);
        return { index: i, ratio };
      }
    }
    return { index: sections.length - 1, ratio: 1 };
  }

  function lerpColor(c1, c2, t) {
    const a = c1.match(/\w\w/g).map(x => parseInt(x, 16));
    const b = c2.match(/\w\w/g).map(x => parseInt(x, 16));
    const m = a.map((v, i) => Math.round(v + (b[i] - v) * t));
    return `#${m.map(x => x.toString(16).padStart(2, "0")).join("")}`;
  }

  function updateBackground() {
    const { index, ratio } = getSectionProgress();
    const current = sections[index];
    const next = sections[index + 1] || current;

    const [bg1Start, bg1End] = current.dataset.bg.split(",");
    const [bg2Start, bg2End] = next.dataset.bg.split(",");

    const text1 = current.dataset.text.trim();
    const text2 = next.dataset.text.trim();

    const blendedStart = lerpColor(bg1Start.trim().replace("#", ""), bg2Start.trim().replace("#", ""), ratio);
    const blendedEnd = lerpColor(bg1End.trim().replace("#", ""), bg2End.trim().replace("#", ""), ratio);
    const blendedText = lerpColor(text1.replace("#", ""), text2.replace("#", ""), ratio);

    // Alternate between layers for smooth crossfade
    const activeLayer = useA ? bgA : bgB;
    const inactiveLayer = useA ? bgB : bgA;

    activeLayer.style.background = `linear-gradient(180deg, ${blendedStart}, ${blendedEnd})`;
    activeLayer.style.opacity = 1;
    inactiveLayer.style.opacity = 0;

    // When section changes, swap which layer is active
    if (index !== currentIndex) {
      useA = !useA;
      currentIndex = index;
    }

    // Apply blended text color
    document.documentElement.style.setProperty("--exec-text", blendedText);
    document.querySelectorAll(".exec-text h2, .exec-text p, .site-nav a, footer, footer p")
      .forEach(el => el.style.color = blendedText);

    requestAnimationFrame(updateBackground);
  }

  requestAnimationFrame(updateBackground);
});
